### ISSUE TITLE
Rock5b issue

### ISSUE THREAD

**Issue by thomasbergersen** [inindev/debian-image#6]
Hi , The latest 12.6 is very stable on the R5S! However, on the Rock5B, it randomly restarts during boot, occasionally enters the system but then freezes. When running `apt upgrade`, it tends to restart, falling into a loop. Can I use the Linux 6.1.0-xx kernel on the Rock5B?

**Comment by inindev** [comment]
This is almost certainly a power supply issue. What power supply are you using?

**Comment by thomasbergersen** [comment]
Here is the translation:

I am using an Anker A2678 power supply, but I had no issues running the official Debian B1 image https://github.com/radxa-build/rock-5b/releases . Before this, I updated to the latest official SPI firmware. Below are some freeze logs from testing this image. 





2.6213031 usbcore: registered new interface driver usbhid
2.625537] usbhid: USB HID core driver
2.6366131 mmc_host mmc2: Bus speed (slot 0) = 187500Hz (slot req 187500Hz, actual 187580H2 div = 8)
2.6356251 input : Rapoo Rapoo Gaming Nouse as /devices/plat form/fcaeaaaa.usb/xhci-hcd.1.auto/usb5/5-1/5-1:1.0/0883:24AE :4104,0001/1nput/inputa
2.6611951 rockchip-du-pcie a41000000.pie: PCIe Gen.2 x1 link up
2.6667691 mmc2: Failed to initialize a non-removable card
2.666930] rockchip-du-pcie a41000000.pcie: PCI host bridge to bus 0004:40
2.6759931 pci_bus 0004:40: root bus resource [bus 40-4%7
2.680411] pci_bus 0004:40: root bus resource [io x200000-8x2fffffl (bus address [0xf4100080-0×f41fffff1)
2.685423] pci_bus 0004:40: root bus resource [mem 0×f4200000-0×f4ffffff]
2.6899761 pci_bus 0004:40: root bus resource [mem Oxa00000000-0xa3fffffff] (bus address (0x40000000-0x7fffffff])
2.6948991 pci 0004:40:00.0: [1d87:3588] tupe 01 class Bx060400 PCIe Root Port
2.6996641 pci 0004:40:00.0: ROM [mem B×00000000-0x0000ffff pref
2.7043031 pci 0004:40:00.0: PCI bridge to Ibus 01-ff]
2.708829] pci 0004:40:00.0:
bridge window Lio B×0000-0x0fff]
2.7092701 hid-generic 0003:24AE: 4104.0001: input, hidraul: USB HID v1.10 Keyboard [Rapoo Rapoo Gaming Mouse] on usb-xhci-hed.1 .auto-1/inputs
2.709368] pc 0004:40:00.0:
bridge window [mem 0x00000000-0×000fffff]
2.711055] pci 0004:40:00.0:
2.710996〕 input: Rapoo Rapoo Gaming Mouse as /devices/platform/fca@aaaa. usb/xhci-hcd. 1.auto/usb5/5-1/5-1:1.1/0003:24AE:4104.0002/impurt/1npurt1
bridge window Emem Ox80000000-8×000fffff 64bit prefl
2.7124181 input: Rapoo Rapoo Gaming Mouse System Control as /devices/plat form/fc4gdaaa. usb/xhci-hcd.1.auto/usb5/5-1/5-1:1.1/0003 :24RE :4104.0002/ inpurt/input2
2.712895] pci 0004:40:00.0: supports D1 D2
2.7454621 pci 0004:40:00.0: PME# supported from DO D1 D3hot
2.7514771 usb 3-1: New USB device found, idVendor=1a40, idProduct=0101, bedDevice= 1.11
2.752608] pci 0004:40:00.0: Primary bus is hard wired to B
2.7568751 us 3-1: New USB device strings: Mfr=®, Product=1, SerialNumber=8
•756881] us 3-1: Product: USB 2.0 Hub*
2.7573771 pci 0004:40:00.0: bridge configuration invalid ([bus 01-ff), reconfiguring
2.758693] hub 3-1:1.0: USB hub found
2.7632171 pci 0004:41:00.0: [10ec: 8125] type 00 class 0x820000 PCIe Endpoint
2.7639521 hub 3-1:1.0: 4 ports detected
2.764125] pci 0004:41:00.0: BAR 0 Lio B×0000-8x00ff1
2. 773304] input: Rapoo Rapoo Gaming Mouse Consumer Control as /devices/platform/fc400000.usb/xci-hcd.1 .auto/usb5/5-1/5-1:1.1/0003:24AE: 4104.0002/input/input3
2.775040] pci 0004:41:00.0: BAR 2 [mem 0x00000000-0×0000ffff 64bit]
2.7766171 hid-generic 8083:24AE: 4104.0002: input,hiddevd,hidraul: USB HID v1.10 Mouse [Rapoo Rapoo Gaming Mouse] on usb-xhci-hed.1.auto-1/inputi
2.7768111 pci 0004:41:00.0: BAR 4 [mem 0x00000000-0×00003fff 64bit]
2.778457] hid-generic 8083:24RE: 4184.0003: hiddev1, hidrau2: USB HID v1.10 Device [Rapoo Rapoo Gaming Mouse] on usb-xhci-hed.1 .auto-1/ input2
2.7788171 pci 0004:41:00.0: supports D1 D2
2.835060] pci 0004:41:00.0: PME# supported from DO D1 D2 D3hot D3cold
2.8531801 pci _bus 0004:41: bus_res: [bus 41-4f1 end is updated to 41
2.859060] pci 0004:40:00.0: bridge window [mem Oxf4200000-0×42fffff]: assigned
2.8650621 pci 0004:40:00.0: ROM [mem Oxf4300000-0xf430ffff pref]: assigned
2.871059] pci B0e4:40:00.0: bridge window [io 0x200000-0x200fff]：assigned
2.8770341 pci 0004:41:00.0: BAR 2 [mem Oxf4200000-0×f420ffff 64bit]: assigned
2.8830861 pci 0004:41:00.0: BAR 4 [mem Oxf4210000-0×f4213fff 64bit]: assigned
2.889113] pci 0004:41:00.0: BAR 0 [io 0x200000-0x2000ff]: assigned
2.8949591 pci 0004:40:00.0: PCI bridge to [bus 411
2.9007401 pci 0004:40:00.0:
bridge window lio 0x200000-0x200fff]
2.9065651 pci 0004:40:00.0:
bridge window [mem Oxf4200000-0x42fffff]
2.913738] pcieport 0004:40:00.0: PM: Signaling with IQ 122
2.9197651 pcieport 0004:40:00.0: AER: enabled with IQ 123
2.925684] r8169 0004:41:00.0: enabling device (0000 -> 0003)
2.9546651 r8169 0004:41:00.0 eth: RTL8125B, 00: e0: 4c:68:02:37, XID 641, IRQ 124
2.9602941 r8169 0004:41:00.0 enP4p65s: renamed from ethe
2.960471] r8169 0004:41:00.0 enP4p650: jumbo features [frames: 9194 bytes, t× checksumming: ko]
3.065102] us 8-1: new low-speed USB device number 2 using ohci-platform
3.3134001 us 8-1: New USB device found, idVendor=1a2c, idProduct=2c27, bedDevice= 1.10
3.319180] us 8-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
3.3247931 usb 8-1: Product: USB Keyboard
3.330113] usb 8-1:
Manufacturer: USB
3.3467631 input: USB USB Keuboard as /devices/platform/fc8c0008.usb/usb8/B-1/8-1:1.8/8809:1A2C:2027.0084/input/input5
3.4095191 hid-generic 0003:1A2C:2C27.0884: input,hidraw: USB HID v1.18 Keyboard [USB USB KeyboardI an usb-fc&c@000.usb-1/1nput@
3.42278a1 input : use usB keyboard Consumer 
3.4892381 input: USB USB Keyboard System Control as /devices/platform/feBceane.usb/usbB/B-1/8-111,1/000311R2C:2C27.0005/input/input?
3.5001481 hid-generic 0003:1A2:227.0005: input,hidrau4: USB HID v1, 10 Device LUSB USB Keyboard] on usb-fc@c0000.usb-1/input1
31.7094151 vdd_gpu_s®: disabling
63.525155] random: crng init done

**Comment by thomasbergersen** [comment]
Please test for RK3588 img boot and desktop environment when you have time. A clean Debian image would be very useful! Thank you.

**Comment by inindev** [comment]
There are known issues powering the rock-5b with a usb-c pd supply using upstream binaries. Sebastian Reichel has been working to resolve them, and you can read more about that here: https://lore.kernel.org/all/a3fd51a4-ecbc-47e1-afba-03c9a4fccd2c@denx.de/T/

I have applied all of these patches to u-boot and the kernel and have it working in my setup with a usb-c pd supply. Can you get the output to the serial console to verify the u-boot you are using?

There was a table of known working power supplies I saw at some point, but I seem to be able to find it right now. I would suggest testing with a different power supply to rule this out.

**Comment by thomasbergersen** [comment]
"Okay, I'll test the Radxa image and USB-C PD logs with version 12.6 later. Additionally, can the RK3588 use an LTS kernel? 😁"

**Comment by thomasbergersen** [comment]
Hi, This is out log:

Radxa image log

thomasbergersenerock-Sb:-$ dmesg I grep -i pd dmesg: read kernel buffer failed: Operation not permitted thomasbergersen@rock-5b:-S sudo dmesg | grep -i pd [sudo] password for thomasbergersen:
8.610944] rockchip-vop2 dd90000. vop: (drm:vop2_ertc_atomic_enable) Update mode to 3840x2160p60, type: 11(1:1000, (lag: 0x0) for up1 de1k: 533290000
8.717882] pi_bus 0002:21: busn_res: (bus 21-2f] end is updated to 21
8.845046] rockchip-vop2 fdd90000. vop: (drm:vop2_erte_atomic_enable] Update mode to 3840X2160p60, type: 11(1f:1000, flag:0x0) for vp1 delk: 533290000
8.979036] rockchip-drm display-subsystem: (drm] fb: rockchipdrmfb frame buffer device
9.477874] pci _bus 0004:41: busn_res: (bus 41-4] end is updated to 41
12.361153] systemd(1]: Starting systemd-boot-update. service - Automatic Boot Loader Update.
23.941598] Bluetooth: hcil: BCM: failed to write update baudrate (-110)
39.8286871 rockchip-vop2 fddsoo0o.vop: tdzm:vop2_crtc_atomic_enable] update mode to 1920x1080p60, type： 11(1f:1000。 flag:0x0) for vp1 dclk: 148500060
711.839189] rockchip-vop2 fddga0o0.vop: ldrm:vop2_crtC_atomic_enable] update mode to 1920x1080p60, type: 11(1f:1000, flag:0x0) for vp1 dclk: 148scac00thomasbezgersenerock-sb:~$ sudo jourmalctl
-xe I grep -i pd
Jul 07 02:11:05 Jock-5b NetwozkManager (906]: ‹info>
Jul 07 02:11:05 zock-5b Networkanagez [906]: sinfos
[1720289465.1283] monitoring ifupdown state f1le "/zun/network/ifstate‘ .
[1720289465.3278] settings: Loaded settings plugin: ifupdown (" /us/lib/aarch64-linux-gnu/NetworkHana
Jul 07 02:11:05 rock-5b NetworkManager (906]: «info>
(1720289465.3279] ifupdown: management mode: unmanaged
Jul 07 02:11:05 rock-5b NetworkManager (906]: «info>
[1720289465.3318] ifupdown: interfaces file letc/netwozk/intertaces doesn't exist
Jul 07 02:11:10 Jock-5b wa_supplicant (909]: w1P2p330: CTRL-EVENT-SUBNET-STATUS-UPDATE status-0
Jul 07 02:11:11 rock-5b systemd(1]: Starting systemd-update-utmp-zunlevel.service - Record Runlevel Change in UTMP . . .
subject: A start job for unit systemd-update-utmp-runlevel.service has begun execution
A start job for unit systemd-update-utmp-runlevel.service has begun execution.
Ju1 07 02:11:11 5ock-5b systemd T1J: systemd-update-utmp-zunlevel.service: Deactivated successtulzy.
The unit systend-update-utmp-sunlevel. service has successfully entered the dead state•
Ju1 07 02:11:11 rock-5b systemd (1]: Finished systemd-update-utmp-zunlevel.service - Record Runlevel Change in UTMP .
Subject: A start job for unit systend-update-utmp-runleve1.service has finished successfully
A start job for unit systemd-update-utmp-runlevel.service has finished successfully•
Jul 07 02:11:14 rock-5b kezne1: Bluetooth: hci1: BCM: failed to write update baudzate (-110)
J01 07 02:11:30 rock-5b systemd T13621: Starting app-user lx2ddirsix2dupdatelx2dgtkeautostart.service • user foldezs update.
Jul 07 02:11:30 rock-5b systemd 13621: Starting app-xdgux2duserlx2ddizslx2dkdeeautostart.service • User folders update..•Jul 07 02:11:30 rock-5b systemd f13621: app-uservx2ddizsVx2dupdatevx2dgtkeautostazt.service: Skipped due to 'exec-condition° •
Ju1 07 02:11:30 Iock-5b systemd t13621: Condition check resulted in app-userlx2ddizs1x2dupdate lx2dgtkeautostart.service • User folders update being skipped.
Ju1 07 02:11:30 rock-5b systemd T13621: Started app-xdgix2duserlx2ddizslx2dkdeeautostart.service • Usez foldezs update.
su o7 02:11:30 zoclk-56 kezme1: zoclchip-vop2 fddooooo.vop: Idzm:Vop2_ crtC-atomic-enable] Update mode to 1920x1080p60, type: 12(1f:1000• flag:Qn02 torr Wps delk： 1485cggceJul 07 02:11:30 zock-5b kscreen_ backend 1aunche [1543]: kscreen.xrandz: XRandRGItE
m_timestamp update 0 => 32647
Jui 07 02:11:30 zock-5D kSCTeen backend_ IaunchezT15431: kscreen.xrandr: xRandROutput 67 update
Ju1 07 02:11:30 tock-5b kSCTeen_ backend 1aunchez[1543J: kscreen. xrandz: xRandRCrtC 63 m_configTimestamp update 0 o 8199
Jul 07 02:11:30 rock-sb kscreen_ backend_ launchez [1543]: kscreen.xzandr: xRandRoutput 66 updateJul 07 02:11:30 rock-5b ksczeen _ backend_Iaunchez[15431: kscreen. xzandz: xRandRoutput 67 updateJuL 07 02:11:30 rock-5b kscreen _backend_launcher [1543]: ksczeen. xrandz: xRandRoutput 66 updateJu1 07 02:11:30 rock-5b kscreen_ backend_ 1aunchez [1543]: ksczeen . xrandz: xRandROutput 67 updateu1 07 02:11:32 rock-5b Packagekit T1600]: get-updates transaction /339_dbaabddb from uid 1001 finished with success after 1719msJu1 07 02:17:10 zock-56 packagekit [16001: getoupdates tsansactson 1341-abeeacda frorm usd 1001 tinished with success arter sorSmsJu1 07 02:17:11 rock-sb PackageKit (1600]: get-updates transaction /342_addbeaee from uid 1001 finished with success aftez 1201msJu1 07 02:22:41 rock-5b kernel: rockchip-vop2 fdd9eo00.vop: Idzm:vop2_cztE-atomdc-enable] Update mode to 1920x1089p60, type: 22(1f:2900. t1ag:0x0) for Vpl dczk: 148500000



v12.6 rock image:

debian@bookworm-rock-5b:"$ sudo dmesg I grep -i pd
1.8483431 PM: gend: Disabling unused power domains
2.721253] rockchip-drm display subsystem: bound fdd90000. vop (ops vop2_component_ops [rockchipdrm])
2. 7297241 rockchip-dre display-subsystem: bound fde80000.hdmi (ops du_hdmi_rockchip_ops [rockchipdrm])
2.968992] rockchip-drm display-subsystem: [drm] fb: rockchipdrmfb frame buffer device
[
4.400810] pci_bus 0002:21: bus_res: [bus 21-21 end is updated to 21
5.248889] pci_bus 0004:41: bus_res: [bus 41-4f] end is updated to 41
[
9.1613721 energy_model: updating cpuß cpu_cap-397 old capacity-530 debian@bookuorm-rock-5b:*$ sudo journalctl -xe I grep -i pd
Jun 16 09:44:32 bookworm-rock-5b kernel: PM: gend: Disabling unused power domains
Jun 16 89:44:32 bookworm-rock-5b kernel: rockchip-drm display-subsystem: bound fdd90000. vop (ops vop2_component_ops (rockchipdral)
Jun 16 B9:44:32 bookworm-rock-5b kernel: rockchip-drm display-subsystem: bound fde80088.hdmi (ops du_hdmi_rackchip_ops [rackchipdrm))
Jun 16 B9:44:32 bookworm-rock-5b kernel: rockchip-drm display-subsystem: [drm] fb8: rockchipdrmfb frame buffer device
Jun 16 09:44:32 bookworm-rock-5b kernel: pci_bus 0002:21: bus_res: [bus 21-2f] end is updated to 21
Jun 16 09:44:32 bookworm-rock-5b kernel: pci_bus 0004:41: bus_res: [bus 41-4f] end is updated to 41
Jun 16 09:44:33 bookworm-rock-5b systemd[1]: Starting ifupdown-pre.service - Helper to synchronize boot up for ifupdaun
Subject: A start job for unit ifupdown-pre.service has begun execution
A start job for unit ifupdown-pre. service has begun execution.
Jun 16 09:44:33 bookworm-rock-5b systemd[1]: Finished ifupdown-pre.service - Helper to synchronize boat up for ifupdawn
Subject: A start job for unit ifupdown-pre.service has finished successfully
A start job for unit ifupdown-pre. service has finished successfully.
Jun 16 09:44:33 bookworm-rock-5b systemd[11: Starting systemd-update-utmp.service - Record System Boat/Shutdoun in UTIP..
Subject: A start job for unit susted-update-utmp.service has begun execution
A start job for unit systemd-update-utmp. service has begun execution.
Jun 16 09:44:33 bookworm-rock-5b systemd[11: Finished systemd-update-utmp.service - Record System Boot/Shutdoun in UTMP.
Subject: A start job for unit systemd-update-utmp.service has finished successfully
A start job for unit susted-update-ump.service has finished successfully.
Jun 16 09:44:34 bookworm-rock-5b kernel: energy_model: updating cpud cpu_cap-397 old capacity 530
Jun 16 09:44:36 bookworm-rock-5b systemd[11: Starting systemd-update-ump-runlevel.service - Record Runlevel Change in UTMP...
Subject: A start job for unit systemd-update-utmp-runlevel.service has begun execution
A start job for unit systemd-update-utmp-runlevel, service has begun execution.
Jun 16 09:44:36 bookworm-rock-5b systemd[1]: systemd-update-utmp-runlevel.service: Deactivated successfully.
_ The unit systend-update-utmp-runlevel,service has successfully entered the 'dead' state.
Jun 16 09:44:36 bookworm-rock-5b systemd[1]; Finished systemd-update-utmp-runlevel,service - Record Runlevel Change in UTMP.
Sub ject: A start job for unit systend-update-utmp-runlevel , service has finished successfullyA start job for unit systend-update-utmp-runleve1,service has finished succesafully
